# Generated by Django 4.2.15 on 2024-10-06 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('fa_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.SmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('descritption', models.TextField(blank=True)),
                ('modules', models.ManyToManyField(to='dashboard_mgmt.module')),
            ],
        ),
        migrations.CreateModel(
            name='SubSystem',
            fields=[
                ('subsystem_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('fa_title', models.CharField(blank=True, max_length=100)),
                ('descritption', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization_mgmt.department')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard_mgmt.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='subsystems',
            field=models.ManyToManyField(to='dashboard_mgmt.subsystem'),
        ),
        migrations.AddField(
            model_name='module',
            name='subsystem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_mgmt.subsystem'),
        ),
    ]
